PaliGemma 2: Does Higher Resolution Mean Better Eyes?

## Research Question
How does increasing image resolution from 224×224 to 448×448 affect
PaliGemma 2 3B on OCR, visual reasoning, and mixed read-and-reason tasks?

## Setup
- Model: PaliGemma 2 3B Mix
- Resolutions: 224×224 and 448×448\
- Images: 3
- Tasks per image: OCR, reasoning, mixed
- Total questions: 9 per model condition

In [19]:
!pip -q install -U transformers accelerate huggingface_hub pillow

In [20]:
%pip install --no-cache-dir --force-reinstall "Pillow==11.3.0"

Collecting Pillow==11.3.0
  Downloading pillow-11.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.0 kB)
Downloading pillow-11.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 50.2 MB/s eta 0:00:00
Installing collected packages: Pillow
  Attempting uninstall: Pillow
    Found existing installation: pillow 12.3.0
    Uninstalling pillow-12.3.0:
      Successfully uninstalled pillow-12.3.0
Successfully installed Pillow-11.3.0

In [21]:
from huggingface_hub import login

login()

In [22]:
import torch

print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

CUDA available: True
GPU: Tesla T4

In [23]:
import os
print(os.listdir("/content"))

['.config', 'results.csv', 'paligemma2-resolution-experiment', 'sample_data']

In [24]:
import os
from PIL import Image

# Clone the repository if it is not already available
if not os.path.exists("/content/paligemma2-resolution-experiment"):
    !git clone https://github.com/hicret11/paligemma2-resolution-experiment.git

BASE_PATH = "/content/paligemma2-resolution-experiment/images"

menu_image = Image.open(
    f"{BASE_PATH}/Image 01 – Menu.jpg"
).convert("RGB")

invoice_image = Image.open(
    f"{BASE_PATH}/Image2 Turkish invoice.webp"
).convert("RGB")

chart_image = Image.open(
    f"{BASE_PATH}/Image 3 Year-value chart.jpg"
).convert("RGB")

print("✅ All 3 experiment images loaded!")

✅ All 3 experiment images loaded!

In [37]:
import torch
from transformers import pipeline

MODEL_ID = "google/paligemma2-3b-mix-224"

pipe = pipeline(
    task="image-text-to-text",
    model=MODEL_ID,
    device=0,
    dtype=torch.bfloat16
)

print("✅ 224 model loaded!")

Loading weights:   0%|          | 0/727 [00:00<?, ?it/s]

✅ 224 model loaded!

In [26]:
# ==========================================
# TEST QUESTIONS — 3 IMAGES, 9 QUESTIONS
# ==========================================

tests = [
    # IMAGE 1 — MENU
    {
        "image_name": "Menu",
        "image": menu_image,
        "task": "OCR",
        "question": "What is the price of Wagyu beef?",
        "expected": "$5.89"
    },
    {
        "image_name": "Menu",
        "image": menu_image,
        "task": "Reasoning",
        "question": "What is the cheapest main dish on the menu?",
        "expected": "Porterhouse ($5.69)"
    },
    {
        "image_name": "Menu",
        "image": menu_image,
        "task": "Mixed",
        "question": "How many main dishes cost less than $10?",
        "expected": "3"
    },

    # IMAGE 2 — TURKISH INVOICE
    {
        "image_name": "Turkish Invoice",
        "image": invoice_image,
        "task": "OCR",
        "question": "What is the invoice number?",
        "expected": "003"
    },
    {
        "image_name": "Turkish Invoice",
        "image": invoice_image,
        "task": "Reasoning",
        "question": "Which item has the highest total price?",
        "expected": "Ana Yemekler"
    },
    {
        "image_name": "Turkish Invoice",
        "image": invoice_image,
        "task": "Mixed",
        "question": "How many items were ordered in total?",
        "expected": "12"
    },

    # IMAGE 3 — CHART
    {
        "image_name": "Year-value Chart",
        "image": chart_image,
        "task": "OCR",
        "question": "What is the value shown for 2014?",
        "expected": "49"
    },
    {
        "image_name": "Year-value Chart",
        "image": chart_image,
        "task": "Reasoning",
        "question": "Which year has the highest value?",
        "expected": "2016"
    },
    {
        "image_name": "Year-value Chart",
        "image": chart_image,
        "task": "Mixed",
        "question": "How many years have a value greater than 30?",
        "expected": "4"
    }
]

# ==========================================
# RUN EXPERIMENT — 224×224
# ==========================================

results_224 = []

for test in tests:
    result = pipe(
        test["image"],
        text="<image>answer en " + test["question"] + "\n",
        max_new_tokens=30
    )

    generated = result[0]["generated_text"]

    if test["question"] in generated:
        answer = generated.split(test["question"], 1)[-1].strip()
    else:
        answer = generated.strip()

    # Save each model answer automatically
    results_224.append(answer)

    print("=" * 65)
    print("Image:", test["image_name"])
    print("Task:", test["task"])
    print("Question:", test["question"])
    print("Expected:", test["expected"])
    print("Answer:", answer)

print("\n✅ 224 experiment completed!")
print("Total answers saved:", len(results_224))

[transformers] Both `max_new_tokens` (=30) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=30) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=================================================================
Image: Menu
Task: OCR
Question: What is the price of Wagyu beef?
Expected: $5.89
Answer: $11.99

[transformers] Both `max_new_tokens` (=30) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=================================================================
Image: Menu
Task: Reasoning
Question: What is the cheapest main dish on the menu?
Expected: Porterhouse ($5.69)
Answer: baby beef ribs

[transformers] Both `max_new_tokens` (=30) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=================================================================
Image: Menu
Task: Mixed
Question: How many main dishes cost less than $10?
Expected: 3
Answer: 3

[transformers] Both `max_new_tokens` (=30) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=================================================================
Image: Turkish Invoice
Task: OCR
Question: What is the invoice number?
Expected: 003
Answer: 14

[transformers] Both `max_new_tokens` (=30) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=================================================================
Image: Turkish Invoice
Task: Reasoning
Question: Which item has the highest total price?
Expected: Ana Yemekler
Answer: Üzerinde 2 tabak yemek

[transformers] Both `max_new_tokens` (=30) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=================================================================
Image: Turkish Invoice
Task: Mixed
Question: How many items were ordered in total?
Expected: 12
Answer: 12

[transformers] Both `max_new_tokens` (=30) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=================================================================
Image: Year-value Chart
Task: OCR
Question: What is the value shown for 2014?
Expected: 49
Answer: 49

[transformers] Both `max_new_tokens` (=30) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=================================================================
Image: Year-value Chart
Task: Reasoning
Question: Which year has the highest value?
Expected: 2016
Answer: 2016
=================================================================
Image: Year-value Chart
Task: Mixed
Question: How many years have a value greater than 30?
Expected: 4
Answer: 4

✅ 224 experiment completed!
Total answers saved: 9

In [38]:
# ==========================================
# ADDITIONAL ANALYSIS — 224 MODEL
# ==========================================

questions_224 = [
    ("Price Reading", "What is the price of Porterhouse?", "$5.69"),
    ("Price Reading", "What is the price of New Zealand lamb?", "$10.99"),
    ("Price Reading", "What is the price of Wagyu beef?", "$5.89"),
    ("Price Reading", "What is the price of Natural cut bone-in ribeye?", "$6.50"),
    ("Simple Comparison", "Which is cheaper, $5.69 or $10.99?", "$5.69"),
    ("Simple Comparison", "Which is cheaper, $5.69 or $5.89?", "$5.69"),
    ("Visual Reasoning", "What is the cheapest main dish on the menu?", "Porterhouse"),
    ("Visual Reasoning", "What is the most expensive main dish on the menu?", "Baby back ribs"),
    (
        "Text-Assisted Reasoning",
        "Main dishes and prices: "
        "Baby back ribs $15.99, "
        "Parmesan-herb angus $12.99, "
        "New Zealand lamb $10.99, "
        "Porterhouse $5.69, "
        "Tenderloin $13.59, "
        "Wagyu beef $5.89, "
        "Natural cut bone-in ribeye $6.50. "
        "Which main dish is the cheapest?",
        "Porterhouse"
    )
]

additional_results_224 = []

for category, question, expected in questions_224:

    result = pipe(
        menu_image,
        text="<image>answer en " + question + "\n",
        max_new_tokens=50
    )

    generated = result[0]["generated_text"]

    if question in generated:
        answer = generated.split(question, 1)[-1].strip()
    else:
        answer = generated.strip()

    additional_results_224.append({
        "Category": category,
        "Question": question,
        "Expected": expected,
        "224 Answer": answer
    })

import pandas as pd

df_additional_224 = pd.DataFrame(additional_results_224)

display(df_additional_224)

df_additional_224.to_csv(
    "/content/additional_analysis_224.csv",
    index=False
)

print("✅ 224 additional analysis completed!")

[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

,Category,Question,Expected,224 Answer
0,Price Reading,What is the price of Porterhouse?,$5.69,$28.95
1,Price Reading,What is the price of New Zealand lamb?,$10.99,$18.90
2,Price Reading,What is the price of Wagyu beef?,$5.89,$11.99
3,Price Reading,What is the price of Natural cut bone-in ribeye?,$6.50,$11.99
4,Simple Comparison,"Which is cheaper, $5.69 or $10.99?",$5.69,$5.69
5,Simple Comparison,"Which is cheaper, $5.69 or $5.89?",$5.69,5.69
6,Visual Reasoning,What is the cheapest main dish on the menu?,Porterhouse,baby beef ribs
7,Visual Reasoning,What is the most expensive main dish on the menu?,Baby back ribs,filet mignon
8,Text-Assisted Reasoning,"Main dishes and prices: Baby back ribs $15.99,...",Porterhouse,new zealand lamb

✅ 224 additional analysis completed!

In [27]:
import gc
import torch

if "pipe" in globals():
    del pipe

gc.collect()
torch.cuda.empty_cache()

print("✅ 224 model cleaned!")

✅ 224 model cleaned!

In [28]:
from transformers import pipeline
import torch

MODEL_ID = "google/paligemma2-3b-mix-448"

pipe = pipeline(
    task="image-text-to-text",
    model=MODEL_ID,
    device=0,
    dtype=torch.bfloat16
)

print("✅ PaliGemma 2 3B–448 loaded!")

Loading weights:   0%|          | 0/727 [00:00<?, ?it/s]

✅ PaliGemma 2 3B–448 loaded!

In [29]:
# ==========================================
# RUN EXPERIMENT — 448×448
# ==========================================

results_448 = []

for test in tests:
    result = pipe(
        test["image"],
        text="<image>answer en " + test["question"] + "\n",
        max_new_tokens=30
    )

    generated = result[0]["generated_text"]

    if test["question"] in generated:
        answer = generated.split(test["question"], 1)[-1].strip()
    else:
        answer = generated.strip()

    # Save model answer
    results_448.append(answer)

    print("=" * 65)
    print("Image:", test["image_name"])
    print("Task:", test["task"])
    print("Question:", test["question"])
    print("Expected:", test["expected"])
    print("Answer:", answer)

print("\n✅ 448 experiment completed!")
print("Total answers saved:", len(results_448))

[transformers] Both `max_new_tokens` (=30) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=30) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=================================================================
Image: Menu
Task: OCR
Question: What is the price of Wagyu beef?
Expected: $5.89
Answer: $5.89

[transformers] Both `max_new_tokens` (=30) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=================================================================
Image: Menu
Task: Reasoning
Question: What is the cheapest main dish on the menu?
Expected: Porterhouse ($5.69)
Answer: new zealand lamb

[transformers] Both `max_new_tokens` (=30) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=================================================================
Image: Menu
Task: Mixed
Question: How many main dishes cost less than $10?
Expected: 3
Answer: 3

[transformers] Both `max_new_tokens` (=30) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=================================================================
Image: Turkish Invoice
Task: OCR
Question: What is the invoice number?
Expected: 003
Answer: 003

[transformers] Both `max_new_tokens` (=30) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=================================================================
Image: Turkish Invoice
Task: Reasoning
Question: Which item has the highest total price?
Expected: Ana Yemekler
Answer: toplam

[transformers] Both `max_new_tokens` (=30) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=================================================================
Image: Turkish Invoice
Task: Mixed
Question: How many items were ordered in total?
Expected: 12
Answer: 2

[transformers] Both `max_new_tokens` (=30) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=================================================================
Image: Year-value Chart
Task: OCR
Question: What is the value shown for 2014?
Expected: 49
Answer: 49

[transformers] Both `max_new_tokens` (=30) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=================================================================
Image: Year-value Chart
Task: Reasoning
Question: Which year has the highest value?
Expected: 2016
Answer: 2016
=================================================================
Image: Year-value Chart
Task: Mixed
Question: How many years have a value greater than 30?
Expected: 4
Answer: 4

✅ 448 experiment completed!
Total answers saved: 9

## Additional Analysis — Reading vs. Reasoning

This section investigates whether incorrect menu answers are related
to visual reading, numerical comparison, or multi-item selection.

The additional tests compare PaliGemma 2 3B Mix at both 224×224 and 448×448 resolutions. These exploratory tests are not included in the main accuracy score.

In [36]:
# ==========================================
# ADDITIONAL ANALYSIS — 448 MODEL
# ==========================================

import pandas as pd

additional_tests = [
    {
        "category": "Price Reading",
        "question": "What is the price of Porterhouse?",
        "expected": "$5.69"
    },
    {
        "category": "Price Reading",
        "question": "What is the price of New Zealand lamb?",
        "expected": "$10.99"
    },
    {
        "category": "Price Reading",
        "question": "What is the price of Wagyu beef?",
        "expected": "$5.89"
    },
    {
        "category": "Price Reading",
        "question": "What is the price of Natural cut bone-in ribeye?",
        "expected": "$6.50"
    },
    {
        "category": "Simple Comparison",
        "question": "Which is cheaper, $5.69 or $10.99?",
        "expected": "$5.69"
    },
    {
        "category": "Simple Comparison",
        "question": "Which is cheaper, $5.69 or $5.89?",
        "expected": "$5.69"
    },
    {
        "category": "Visual Reasoning",
        "question": "What is the cheapest main dish on the menu?",
        "expected": "Porterhouse"
    },
    {
        "category": "Visual Reasoning",
        "question": "What is the most expensive main dish on the menu?",
        "expected": "Baby back ribs"
    },
    {
        "category": "Text-Assisted Reasoning",
        "question": (
            "Main dishes and prices: "
            "Baby back ribs $15.99, "
            "Parmesan-herb angus $12.99, "
            "New Zealand lamb $10.99, "
            "Porterhouse $5.69, "
            "Tenderloin $13.59, "
            "Wagyu beef $5.89, "
            "Natural cut bone-in ribeye $6.50. "
            "Which main dish is the cheapest?"
        ),
        "expected": "Porterhouse"
    }
]

additional_results = []

for test in additional_tests:

    result = pipe(
        menu_image,
        text="<image>answer en " + test["question"] + "\n",
        max_new_tokens=50
    )

    generated = result[0]["generated_text"]

    if test["question"] in generated:
        answer = generated.split(
            test["question"], 1
        )[-1].strip()
    else:
        answer = generated.strip()

    additional_results.append({
        "Category": test["category"],
        "Question": test["question"],
        "Expected": test["expected"],
        "Model Answer": answer
    })

additional_df = pd.DataFrame(additional_results)

display(additional_df)

additional_df.to_csv(
    "/content/additional_analysis_448.csv",
    index=False
)

print("✅ Additional analysis completed!")
print("Total tests:", len(additional_df))
print("✅ Saved: additional_analysis_448.csv")

[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=50) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

,Category,Question,Expected,Model Answer
0,Price Reading,What is the price of Porterhouse?,$5.69,$5.69
1,Price Reading,What is the price of New Zealand lamb?,$10.99,$10.99
2,Price Reading,What is the price of Wagyu beef?,$5.89,$5.89
3,Price Reading,What is the price of Natural cut bone-in ribeye?,$6.50,$8.50
4,Simple Comparison,"Which is cheaper, $5.69 or $10.99?",$5.69,$5.69
5,Simple Comparison,"Which is cheaper, $5.69 or $5.89?",$5.69,5.89
6,Visual Reasoning,What is the cheapest main dish on the menu?,Porterhouse,new zealand lamb
7,Visual Reasoning,What is the most expensive main dish on the menu?,Baby back ribs,parmesan-herb angus
8,Text-Assisted Reasoning,"Main dishes and prices: Baby back ribs $15.99,...",Porterhouse,new zealand lamb

✅ Additional analysis completed!
Total tests: 9
✅ Saved: additional_analysis_448.csv

In [39]:
# ==========================================
# ADDITIONAL ANALYSIS — COMPARISON
# ==========================================

import pandas as pd

comparison = df_additional_224.merge(
    additional_df,
    on=["Category", "Question", "Expected"],
    how="inner"
)

comparison = comparison.rename(
    columns={"Model Answer": "448 Answer"}
)

display(comparison)

comparison.to_csv(
    "/content/additional_comparison.csv",
    index=False
)

print("✅ Additional comparison saved!")
print("Total compared questions:", len(comparison))

,Category,Question,Expected,224 Answer,448 Answer
0,Price Reading,What is the price of Porterhouse?,$5.69,$28.95,$5.69
1,Price Reading,What is the price of New Zealand lamb?,$10.99,$18.90,$10.99
2,Price Reading,What is the price of Wagyu beef?,$5.89,$11.99,$5.89
3,Price Reading,What is the price of Natural cut bone-in ribeye?,$6.50,$11.99,$8.50
4,Simple Comparison,"Which is cheaper, $5.69 or $10.99?",$5.69,$5.69,$5.69
5,Simple Comparison,"Which is cheaper, $5.69 or $5.89?",$5.69,5.69,5.89
6,Visual Reasoning,What is the cheapest main dish on the menu?,Porterhouse,baby beef ribs,new zealand lamb
7,Visual Reasoning,What is the most expensive main dish on the menu?,Baby back ribs,filet mignon,parmesan-herb angus
8,Text-Assisted Reasoning,"Main dishes and prices: Baby back ribs $15.99,...",Porterhouse,new zealand lamb,new zealand lamb

✅ Additional comparison saved!
Total compared questions: 9

### Additional Analysis — Findings

The additional experiment compared PaliGemma 2 3B Mix at 224 and 448 resolution using the same menu image and nine additional questions.

| Task | 224 Resolution | 448 Resolution |
|---|---|---|
| Price Reading | 0/4 | 3/4 |
| Simple Comparison | 2/2 | 1/2 |
| Visual Reasoning | 0/2 | 0/2 |
| Text-Assisted Reasoning | 0/1 | 0/1 |
| Overall | 2/9 | 4/9 |

#### Key Observations

**1. Higher resolution improved price reading.**

The 224 model answered all four individual price questions incorrectly, while the 448 model answered three correctly.

**2. Higher resolution did not consistently improve numerical comparison.**

The 224 model correctly compared both pairs of prices. The 448 model correctly compared 5.69 USD and 10.99 USD but failed when comparing 5.69 USD and 5.89 USD.

**3. Both models struggled with selecting dishes from the full menu.**

Neither model correctly identified the cheapest or most expensive main dish.

**4. Providing correct prices did not resolve the selection error.**

Both models selected New Zealand lamb instead of Porterhouse, even when the correct prices were included in the question.

#### Interpretation

These findings suggest that higher image resolution can improve the reading of fine visual details without necessarily improving multi-item selection or numerical reasoning.

However, this is a small exploratory experiment. The text-assisted test still includes the image, and the results may be affected by prompt wording, question length, and model-specific instruction-following behavior.

## Results

The following table compares PaliGemma 2 3B at 224×224 and 448×448
using the same images, questions, and expected answers.

In [30]:
# ==========================================
# RESULTS — PaliGemma 2 Resolution Experiment
# ==========================================

import pandas as pd
from pathlib import Path

# Check both experiments are complete
assert len(results_224) == len(tests), "224 results are missing!"
assert len(results_448) == len(tests), "448 results are missing!"

# Build results table automatically
rows = []

for i, test in enumerate(tests):
    rows.append({
        "Image": test["image_name"],
        "Task": test["task"],
        "Question": test["question"],
        "Expected": test["expected"],
        "224 Answer": results_224[i],
        "448 Answer": results_448[i]
    })

df = pd.DataFrame(rows)

# Automatic scoring for answers that can be checked exactly.
# Other answers must be reviewed manually.
def normalize(value):
    return str(value).strip().lower()

df["224 Correct"] = [
    normalize(answer) == normalize(expected)
    for answer, expected in zip(df["224 Answer"], df["Expected"])
]

df["448 Correct"] = [
    normalize(answer) == normalize(expected)
    for answer, expected in zip(df["448 Answer"], df["Expected"])
]

# Accept the correct dish name without requiring the price
for col in ["224 Correct", "448 Correct"]:
    answer_col = col.replace(" Correct", " Answer")
    df.loc[
        (df["Image"] == "Menu") &
        (df["Task"] == "Reasoning"),
        col
    ] = df.loc[
        (df["Image"] == "Menu") &
        (df["Task"] == "Reasoning"),
        answer_col
    ].apply(
        lambda x: normalize(x) in [
            "porterhouse",
            "porterhouse ($5.69)"
        ]
    )

display(df)

print("\n--- OVERALL ACCURACY ---")
print("224 accuracy:", f"{df['224 Correct'].mean()*100:.1f}%")
print("448 accuracy:", f"{df['448 Correct'].mean()*100:.1f}%")

print("\n--- ACCURACY BY TASK ---")
print(
    df.groupby("Task")[["224 Correct", "448 Correct"]]
    .agg(["sum", "count"])
)

# Save without overwriting original experiment
output_path = Path("/content/results_v2.csv")
df.to_csv(output_path, index=False)

print(f"\n✅ Saved: {output_path}")

,Image,Task,Question,Expected,224 Answer,448 Answer,224 Correct,448 Correct
0,Menu,OCR,What is the price of Wagyu beef?,$5.89,$11.99,$5.89,False,True
1,Menu,Reasoning,What is the cheapest main dish on the menu?,Porterhouse ($5.69),baby beef ribs,new zealand lamb,False,False
2,Menu,Mixed,How many main dishes cost less than $10?,3,3,3,True,True
3,Turkish Invoice,OCR,What is the invoice number?,003,14,003,False,True
4,Turkish Invoice,Reasoning,Which item has the highest total price?,Ana Yemekler,Üzerinde 2 tabak yemek,toplam,False,False
5,Turkish Invoice,Mixed,How many items were ordered in total?,12,12,2,True,False
6,Year-value Chart,OCR,What is the value shown for 2014?,49,49,49,True,True
7,Year-value Chart,Reasoning,Which year has the highest value?,2016,2016,2016,True,True
8,Year-value Chart,Mixed,How many years have a value greater than 30?,4,4,4,True,True

--- OVERALL ACCURACY ---
224 accuracy: 55.6%
448 accuracy: 66.7%

--- ACCURACY BY TASK ---
          224 Correct       448 Correct
                  sum count         sum count
Task
Mixed               3     3           2     3
OCR                 1     3           3     3
Reasoning           1     3           1     3

✅ Saved: /content/results_v2.csv

## Observations

- OCR accuracy increased from **1/3 at 224×224** to **3/3 at 448×448**.
- Overall accuracy increased from **5/9 (55.6%)** to **6/9 (66.7%)**.
- Reasoning accuracy remained **1/3** for both resolutions.
- Mixed-task accuracy decreased from **3/3** to **2/3**.
- On the Turkish invoice counting question, the 224 model answered **12** correctly, while the 448 model answered **2** incorrectly.
- The additional analysis explores whether menu errors arise from reading prices, comparing numbers, or selecting among multiple dishes.

## Limitations

This study is a small exploratory experiment, not a formal benchmark. It uses three images and nine main questions for each resolution, followed by nine additional menu questions for each model.

The sample size is too small to draw general conclusions about PaliGemma 2's overall performance. The results may vary with different images, question wording, and model settings.

Some reasoning questions also depend on reading text from images. Therefore, an incorrect answer does not always indicate a reasoning failure; it may result from OCR errors or difficulties combining visual information.

The additional experiments attempted to investigate this distinction through individual price reading, simple numerical comparisons, and text-assisted questions. However, the text-assisted tests still included the menu image, so they cannot fully isolate reasoning from visual understanding.

Finally, the experiments used only the 3B Mix checkpoints at 224 and 448 resolution. They do not establish how larger PaliGemma 2 models or other checkpoints would behave.

Overall, the findings suggest that higher resolution can improve visual reading accuracy, but better visual perception does not necessarily guarantee better answers to more complex questions.